#!/bin/bash

function brollet_pid {
    val=`ps -ef | grep 'python ../webServer' | grep -v grep | awk '{print $2}'`;
    size=${#val}
    local result=$val
    if [ $size -eq 0 ]
    then
        local result=-1
    fi
    echo $result
}

function show_commands {
    echo "    start [port-number]"
    echo "    stop"
    echo "    clean"
}

function check_log_dir {
    if [ ! -d "logs" ]
    then
	mkdir logs
	echo "Logs directory created."
    fi
}

if [ $# -lt 1 ]
then
    echo "Please specify a brollet command, e.g"
    show_commands
    exit
fi

if [ $1 == "start" ]
then
    if [ $(brollet_pid) -lt 0 ]
    then
	check_log_dir
	./httpd.sh $2 2>> logs/web.log &
    fi
elif [ $1 == "stop" ]
then
    bid=$(brollet_pid)
    kill `brollet_pid`
elif [ $1 == "clean" ]
then
    rm logs/web.log
else
    echo "Unrecognized brollet command, valid commands include"
    show_commands
fi
