#!/bin/env python

# For ubuntu install should be #!/usr/bin/env python

# Found this here: http://code.activestate.com/lists/python-list/284803/

import SocketServer
import BaseHTTPServer
import CGIHTTPServer

class ThreadingCGIServer(SocketServer.ThreadingMixIn,
                   BaseHTTPServer.HTTPServer):
    pass

import sys

if sys.argv[1:]:
    port = int(sys.argv[1])
else:
    port = 8099

server = ThreadingCGIServer(('', port), CGIHTTPServer.CGIHTTPRequestHandler)
try:
    while 1:
        sys.stdout.flush()
        server.handle_request()
except KeyboardInterrupt:
    print "Finished"


